version: '3'

services:
  database:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB_NAME}
      POSTGRES_USER: ${USER_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - khalti-network

  khalti_api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - env=dev
    container_name: khalti_api
    networks:
      - khalti-network

networks:
  khalti-network:
    external: true