# Generated by Django 5.1.3 on 2024-11-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_tickets', to='booking.booking'),
        ),
    ]
